# Generated by Django 6.0.4 on 2026-04-20 15:36

import django.utils.timezone
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='Unique ID in UUID v7.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gender', models.CharField(db_index=True, max_length=50)),
                ('gender_probability', models.FloatField(db_index=True)),
                ('age', models.IntegerField(db_index=True)),
                ('age_group', models.CharField(db_index=True, max_length=50)),
                ('country_id', models.CharField(db_index=True, max_length=2)),
                ('country_name', models.CharField(max_length=255)),
                ('country_probability', models.FloatField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='profile_int_created_2fa3fe_idx'), models.Index(fields=['country_id', 'age_group'], name='profile_int_country_7c046b_idx'), models.Index(fields=['gender', 'age'], name='profile_int_gender_0d4d98_idx')],
            },
        ),
    ]
